name: build site

on:
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Build Docker image
        run: |
          docker build --platform=linux/amd64 -t processing.py.site:latest .
      - name: Run Docker container
        continue-on-error: true #the failed generated images should be warnings instead of errors
        run: |
          docker run --rm -v ${{ github.workspace }}/generated:/processing.py.site/generated processing.py.site:latest
      - name: upload result
        uses: actions/upload-artifact@v4
        with:
          name: website
          path: ${{ github.workspace }}/generated
